import { Footer } from '@/components'
import './globals.css'

export const metadata = {
  title: 'adamkeyes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' bg-primary '>
        {children}
        <Footer />
      </body>
    </html>
  )
}
